# Generated by Django 3.2.1 on 2021-05-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_publish_date_post_publish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-publish",)},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="slug",
            new_name="url",
        ),
    ]
