# Generated by Django 3.2.1 on 2021-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20210520_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=""),
        ),
    ]
