# Generated by Django 3.2.1 on 2021-05-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_used_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
    ]
