# Generated by Django 3.2.1 on 2021-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_auto_20210521_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="county",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="order",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="street_address2",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
