# Generated by Django 3.2.1 on 2021-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_has_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=""),
        ),
    ]
